kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    annotations:
        hub.jupyter.org/username: ENC[AES256_GCM,data:0O0+/PNewnAbu3eEMV/dEvQZ,iv:o22UPC0o8GBXJVqgAAr38Px6/9czhyivjGXZeCnoV7g=,tag:Kb7bC6iQHvJ4oO9O2LwMIw==,type:str]
    name: ENC[AES256_GCM,data:AP111CAnMLhHCDbNCoVZ3UX9PmST4xjneJiGeuOpJ7jdFXRLzZkGow==,iv:oJrOeMH8vXYK1GctGMFUCqy+Y2AKQnIanWf3hFjhiE4=,tag:T5NG5y9R+fTkLNUitOHAYg==,type:str]
    labels:
        app: jupyterhub
        component: singleuser-storage
spec:
    resources:
        requests:
            storage: 32Gi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-20T15:20:45Z'
    mac: ENC[AES256_GCM,data:iuJXf8VBQBrp/f10guTevUT5utOdPAya/iPDbFAzdH0CeFQIG6WReqQcFA8GYI+tdlZvqRfMXgqmmTx9aPXj65/CpLAW6hqYZjUL60ttvqOPv4MoY2NwlVovSsdqC4fBrhEgucEsKkeRFEbArp19gWgFDUzKwO7/aj4dgbyQOEU=,iv:25RK2gOHOUUPK4wer4NCKN2EnSH2EMlgEaZ3v4Xy2IY=,tag:0aoYaGxllUBRKLOv8f6bfg==,type:str]
    pgp:
    -   created_at: '2021-02-17T21:52:59Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiAQ/9HjPOLOf+RI/EGHKeSSgEESdLS2oaiZfkAOg0uMFVtaWx
            bgNMj9NiR6OUuAlVtO1dvfAZ9RKH95agNjRDbJOzTd0FV+OSfgC7Kku84mKk0KTb
            WadGFpuMWDi0clITd/3JKGxLlCB1ZTeVBes4dEDLMlmVKPjEAlsXhY+473SxjSO7
            fz8HGYXcY+5i3zQ4JJvGz1MeDK8nSF8Q7WhbuFG5FP5OjXnqiQp6fK2D0DD95DBx
            q1mY99co92hEg0RO51yMdcji3eD+xomDPnZU0lmRliI94zs4qAwaDAHUCPVkzAc/
            p/irmueiwJcE/lfipNQWDP7FutA88VZa2S/WZd0re3xgdFJo46pZUutvhW68DVfb
            EU1ZIMUwqrbfBCL1HUa2zepeXpTHiCL6U+ercUVftP7+JjkmbiAbdPE9mnL9cGme
            biCGHfFsni29pL1LPR2mhOJ6QaGeuUw8fVgm8jekNAZrea+vynuH8ZWVtaK1MMFc
            vNxU1i1e73J7byd3k7iWoqNZ1IoAY7su0W9s04fqIvG0ltBJTNu5oGFwpdYzURh0
            nhvx7APGGJBhtduhzUoB8+LphLc7h1ke1nhPkDyK5veRalMvkZaJ+5CUHg0yJk2T
            d4fdcAJHPCDOLGOh5KeDysNoqcA3GtoQ/f6MOPDtQh83PKC/X0Cq2wBxvw2oJQTS
            XgGEX5NOuI2/b6/M1XhCtzvdxpAhxZ+ArPOeTuwuPwaw8ouOUp3dehZ7e7hMTRbm
            5are+Efy3sClsA/WEFZJN31ZYGADYYJlVHtktflrUDRR1WEPlLgM/tuwS99YHPs=
            =PWEH
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^annotations|name$
    version: 3.6.1
