apiVersion: v1
kind: Secret
metadata:
    name: cluster-spec-moc-infra
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: moc-infra
    config: ENC[AES256_GCM,data:E5cXEJEgt/n9rPFIgg0OMrYHQLVM/lk68s/25Eo8QVO9wC2tNgfEarPtqUZfyP3oGXeouJuUmu2HoG4zHTUZ3NlbgG9nDKjZhCCfLQRtSQNGXis2PC6eFHih484oHGc7L8B3VlUeXslzz4m+uYcd2t4wlKlMa8TTkNZ5fB9lBwT0LZgsGgocOgxDQyeQx1thRo46yvNoYBuQrfjn/yJ4U1WizFsvxS3weTtnoGKdCCgMSfH8mEkhStd1J//tD/UajL1e6AcduVOrqAZo9El+PXTQFCWC/v3QM+FQduhSA93TyLYLGso2366m6/zQtsAqVb9G2PfcmwP5y+vKAvQTjgTAxinf7cCeyxGUMLZMLeaAj9f8i/PLPfrtFdSmzBJRhfbSVpsy3ful7gZXY0P+xnLs/ok7lAplcy0LQDqUz6TpipULF8iQPjBc4aSqEbc6r5mfbBtgLrGntPmBsNDM6p3WCrz7AvUAbK42sljMBhb1FarOsBqKRymhfI24OhjAxAVx7EY0Gs7NqbQt11c3yyKfV+dbChV0paFWoKGoowc2LTYksiLiFDPQFA18buid50/z0U2D55HaMcu+a0NrnMKg7JPfDqsw4DAqDJkWjUdXZmExY0fl3qCu8ArobHWNFhSymaTkMYM0mq7akmhuhuyVUMEkqqBr3mxFdgr9/I2B89kakxMDMWWb5ho+fPnZsxR6PNCwXqOM5BJ7qFXbWyb67sQpRu3139hSuGchkSYsGwPgjyl/wvGM0rs9+DMh80AHeTDnaUcNcFyz8T2BWdYJEFMPhWoZOgc1FON4eSbpcGqFM+JJOkmJ1ER2ask4AkO5FQWMipp4wPuoa3k2XbOyV/elg7TLY/SKtfVdYHbucixEpMBy5UXxYZxfT6UHF+TBXPmaWri4gEUiTmgOEjR2/gIorPMpg6U+1Tmkdre+WKN7Kxr05pwmejMaZD/6xYGZKk5ejlWNyAxFqjmrJy9KRZpg600FnVbCI/drMEnAIgVE6214uRBUVfy0MDIGXaSPQv/noq4mf4SGkpsQcnsgDbjlNF54UEp/RByvKLq+MN1T0e/sc4m9INV0kVwEx773fQMcFd8mNJYFNdZJB6jab9w6KiadsoIHwJs6WLMRjmvlnVKPZ++6otLRy1LR1Ds0tAyQZM0kI31Zw9RQIySO71QL5GE1uSECHPTtgnQnPlPMVdZfuEG0uXXuPgm1Zbe4Yr8z00kH2RriS7yytJ0TNYgKfrKxXhgSbkRRVHyvRlDKTs4o061b+QGsILOEqOr9jJ/jMMppcFrDRcLgedzyHvy0ac05,iv:ark+a9Q2io7dO3mucEnpjeiXkx9r8jzh5znsWawOxKQ=,tag:Zg1higX/kmB0VOqe8w7sfQ==,type:str]
    server: https://api.moc-infra.massopen.cloud:6443
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-22T23:51:02Z'
    mac: ENC[AES256_GCM,data:2ICGyTQhxobwzgMQ2e1UrXJYQ5ThIuJ4sMoVRQOvdWhkBjJcU9WMWjr9NflHh0gK5VqY9ilWV5FPUeqQLum50XsAsFl4orTPLkYH89eGVo4PtWJ5tCgYA1Tfk+zI+0nvOmvybB/ge/ZFPsgSxFvP2meTb4ym8LsR4RJdEHd0aj8=,iv:oQVpnOZxbrY2hg8QTRpjlcf03BjPUnRF1IPOjRMIyCg=,tag:ssMUEv+Eqz1+T0IuRoQJdw==,type:str]
    pgp:
    -   created_at: '2021-02-22T23:51:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9aKBcudqifiARAAiOsg8cUc9Rb5V0KEWpOmWjjMnG1qXgSHFXyLGJBgfHt+
            ExHNoLMr04rrG+uPlaYlRCIDfKhIEKiSmMNS9j9NeigqVK2sir0FWaB1Mh9LaN8b
            esDeTdVmfRVZCyCHeV1GzwNxEjR+RfqJgZuYZ3GHvkjqfXYjV4LNej1HwrGfJNsK
            XHHxKnaObntmDDo7CD0L0uUL4gwHLLF2c5rIcPXSANHgyS9egLi8aqarQVpEvma/
            ie3AAPuqg/5YDYXT+qNRArjXgM+rrF2Une/v1peqqAb5+mJH1RZXuBVWhawvl9Al
            X6OQ76vOMV2XphoGStg/8DW/xzgXSYyP7avxWZXC3bSIBL6VD108KLn/LmVDxh/n
            FsAFv3b5W2X0b34Xr6SiOzzxJVn+KUmK3q6KIwd5+m1V/drgkbhfmXf0JXaMUIiD
            YKCUBA0Wf+OtmjWI8ezsEzAGLyB0XUx3V5VbzRen0jVnSx7fxhwkgGn1xJzN5yjQ
            7VIpzv+aSlDeZ6HQuHsJACegGK8o/+oR3WtlUmofeS6j9ZBD7Fmvk1hTyX5V00fR
            7/wsQgczU+lrxR3dX8F3UYd3RfcsO9sYG8mJeFGAb3QIGfN/2ntq27sq5N+McwF7
            rN9sXjYKIoQ+hJ5g+tmnR+8nZU/ylakPaQh4N76lB7vgA/DU58YeitKLgoegN37S
            XgEl3FVoLCUiIKvZ2seRo7pjDBXY3baZ4W+qwDGGzfcMIcEieEpPexQF0WWulRwg
            7jLFrrDL8uPvWsH3+moHSd0/TGylJ2/xfOKI4/2mllNbSlCjGrB8fmq5R8ZoMHk=
            =fr6f
            -----END PGP MESSAGE-----
        fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: ^(config)$
    version: 3.6.1
