---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: osc-playground

resources:
  - ../../../../base/jupyterhub

patchesJson6902:
  - patch: |
      - op: add
        path: /spec/applications/2/kustomizeConfig/overlays/-
        value: storage-class
      - op: add
        path: /spec/applications/2/kustomizeConfig/parameters/-
        value:
          name: storage_class
          value: moc-nfs-csi
    target:
      group: kfdef.apps.kubeflow.org
      kind: KfDef
      name: opendatahub
      version: v1
