apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/ray
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/x-small
kind: Kustomization
namespace: ray-odh-integration
resources:
- namespace.yaml
