apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    admin.password: $2a$10$3NRgSgN2t9PhYIZod9W.Tuf.t166yieMbhIu9f8hGC2K8EcdHtXsW
    admin.passwordMtime: 2021-01-12T19:01:39EST
