---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common
  - ../../../base/namespaces/acm
  - ../../../base/namespaces/opf-alertreceiver
  - ../../../base/clusterrolebindings/argocd-application-controller
  - ../../../base/clusterrolebindings/argocd-manager
  - ../../../base/clusterrolebindings/argocd-server
  - ../../../base/clusterrolebindings/cluster-admins-rb
  - ../../../base/clusterroles/argocd-application-controller
  - ../../../base/clusterroles/argocd-events-create-aggregate-to-admin
  - ../../../base/clusterroles/argocd-proj-apps-aggregate-to-admin
  - ../../../base/clusterroles/argocd-server
  - ../../../base/crds/applications.argoproj.io
  - ../../../base/crds/appprojects.argoproj.io
  - ../../../base/groups/cluster-admins
  - ../../../base/oauths/cluster
  - ../../../base/operatorgroups/acm
  - ../../../base/subscriptions/advanced-cluster-management
  - ../../../base/ingresscontrollers/default

  # install cnv for nmstate support in 4.6
  - ../../../base/namespaces/openshift-cnv
  - ../../../base/operatorgroups/openshift-cnv
  - ../../../base/subscriptions/kubevirt-hyperconverged

  - crc-provisioning-vlan.yaml
  - zero-provisioning-vlan.yaml

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - oauths/cluster_patch.yaml
  - subscriptions/kubevirt-hyperconverged_patch.yaml
